# Generated by Django 4.2.4 on 2023-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
