# Generated by Django 4.2.4 on 2023-09-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_getid_productlist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoping_cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('amount', models.IntegerField(max_length=10)),
                ('help', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productlist',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
