# Generated by Django 4.2.4 on 2023-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_productlist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='getID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='description',
            field=models.TextField(default='none', max_length=2000),
        ),
    ]
