# Generated by Django 4.2.4 on 2023-09-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_shoping_cart1_alter_productlist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(max_length=100)),
                ('help', models.CharField(max_length=100)),
            ],
        ),
    ]
